### ISSUE TITLE
Fix create_database.sql scripts #1

### ISSUE THREAD

**Issue by BennyJake** [Sageth/phparcade#16]
I'm looking at helping modernize your application, but am having difficulty getting it up and running per your instructions. I've made headway, but have noticed a few problems with your create_database.sql script.  I believe I have fixes in place for it, ready to merge in. @Sageth

**Comment by Sageth** [comment]
Awesome, appreciate it.  Please feel free to submit a PR and I'd be happy to evaluate and merge.

**Comment by arysom** [comment]
I've tried to manually use sql file, but got an error The used table type doesn't support FULLTEXT indexes . I know that fulltext index is supported from mysql 5.7 and my mysql is unfortunately 5.6 . Are you strict on required versions of php and mysql? Tell us, so maybe I can improve the file a little bit. As I told, make project enter curve less stepper :)

**Comment by Sageth** [comment]
I've thought about this a bit since your questions and I think I need to be strict on the MySQL/MariaDB version and PHP versions (7.0).  I don't have the resources right now to test different versions.  As this is open source, it won't be for everyone and that's fine.  :smile:

**Comment by Sageth** [comment]
Closed via pull request #17
